[package]
name = "adventofcode_rs"
version = "0.1.0"
edition = "2024"


[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[dependencies]
disjoint-sets = "0.4.2"
glam = "0.30.10"
itertools = "0.14.0"


[[bench]]
name = "aoc_benchmarks"
harness = false
