[package]
name = "adventofcode_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.10"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "aoc_benchmarks"
harness = false
